export const actionTypes = {
  INIT_FIREBASE: 'INIT_FIREBASE',
  INIT_TODAY: 'INIT_TODAY',
  INIT_EVENTS: 'INIT_EVENTS',
  INIT_CRITERIAS: 'INIT_CRITERIAS',
  
  CREATE_USER: 'CREATE_USER',
  SET_USER: 'SET_USER',
  
  SET_CRITERIAS: 'SET_CRITERIAS',
  SET_EVENTS: 'SET_EVENTS',
  SET_SETTINGS: 'SET_SETTINGS',
}